/*
 * This source file was generated by the Gradle 'init' task
 */
package taller5;
import java.text.DecimalFormat;
import java.util.Random;
import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
        
        try {
        String resultadoJuego = Jugar_21(5);
        System.out.println(resultadoJuego);       
        encontrarNumero();
        Scanner scanner = new Scanner(System.in);
        System.out.print("Ingrese la cantidad de bombillas: ");
        int bombillas = scanner.nextInt();
        String empaqueResultado = Calcular_empaque(bombillas);
        System.out.println(empaqueResultado);
        String ventasResultado = Simular_ventas();
        System.out.println(ventasResultado);   
        } 
        
        catch (Exception e) {
            
        }
    }

    /*
    
        1.	Desarrolle un algoritmo e impleméntelo en Java que: le pida al usuario un número entero positivo 
        entre 1000 y 9999. En un ciclo genere números de manera aleatoria y cuente los intentos que hizo antes 
        de hallar el número exactamente.
        
    
    */ 

    public static void encontrarNumero() {
        Scanner scanner = new Scanner(System.in);
        Random random = new Random();

        try {
            System.out.print("Ingrese un número entero positivo entre 1000 y 9999: ");
            int numero = scanner.nextInt();

            if (numero < 1000 || numero > 9999) {
                System.out.println("El número debe estar entre 1000 y 9999.");
                return;
            }

            int intentos = 0;
            int numeroAleatorio;

            do {
                numeroAleatorio = random.nextInt(9000) + 1000; 
                intentos++;
            } while (numeroAleatorio != numero);

            System.out.println("El número fue encontrado en " + intentos + " intentos.");
        } catch (Exception e) {
            System.out.println("Error: Debe ingresar un número entero.");
        }
    }




    /* 
     
        2.	Se requiere una función en java que simule las ventas de tres años para un almacén. Para cada año, deberá generar 
        un aleatorio para cada mes hasta completar los 12 meses. La función se llamará Simular_ventas, y debe retornar un String 
        al final que muestre las ventas de cada año, así:
        
            Año 1
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###
            Total ventas Año 1:  $##.###.###
            
            Año 2
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###
            Total ventas Año 2: $##.###.###
            
            Año 3
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###

            Total ventas Año 3: $##.###.###
            
            Investigue sobre la clase DecimalFormat para mostrar bien la salida. 
            import java.text.DecimalFormat;
            DecimalFormat form_pesos = new DecimalFormat("$#,###.00");

        
      
    */

    public static String Simular_ventas() {
        Random random = new Random();
        DecimalFormat formPesos = new DecimalFormat("$#,###.00");
        String resultado = "";

        for (int año = 1; año <= 3; año++) {
            resultado += "Año " + año + "\n";

            double totalVentas = 0;

            for (int mes = 1; mes <= 12; mes++) {
                double venta = random.nextDouble() * 1000000; 
                totalVentas += venta;

                resultado += "Ventas Mes " + mes + ": " + formPesos.format(venta) + "\n";
            }

            resultado += "Total ventas Año " + año + ": " + formPesos.format(totalVentas) + "\n\n";
        }

        return resultado;
    }

    



    /*  
     
        3.	En una fábrica se tiene el siguiente patrón de empaque: En una estiba(o pallet) caben 16  cajas y en cada caja, 
        caben 30 bombillas. Desarrolle una función que se llame: Calcular_empaque que: reciba como argumento la cantidad de 
        bombillas que se deben empacar y a partir de allí: calcule cuántas cajas necesita, cuántas estibas o pallets necesita. 
        Luego escriba lo siguiente: 

        Para ### bombillas, se necesitan ## cajas y ## pallets. Se quedan ### bombillas sin empacar. Se empacará así:

        Pallet 1 --> Caja1, Caja2……,Caja16
        Pallet2 -->  Caja17, Caja18…..Caja 32
        .
        Pallet n -- > Caja m, caja m+1…..
        
        La función retornará un texto, con la información anterior. Pruebe la función llamándola desde el programa principal: solicite al usuario el número de bombillas e invoque la función para imprimir en el main, los resultados.



    */
    public static String Calcular_empaque(int bombillas) {
        try {

            if (bombillas <= 0) {
               return ("La cantidad de bombillas debe ser mayor que 0.");
            }
    
            int cajas = bombillas / 30;
            int pallets = cajas / 16;
            int bombillasSinEmpacar = bombillas % 30;
            String resultado = "";
    
            resultado += "Para " + bombillas + " bombillas, se necesitan " + cajas + " cajas y " + pallets + " pallets. Se quedan " + bombillasSinEmpacar + " bombillas sin empacar.\n";
    
            int caja = 1;
            int pallet = 1;
    
            while (caja <= cajas) {
                resultado += "Pallet " + pallet + " --> ";
    
                for (int i = 0; i < 16; i++) {
                    resultado += "Caja" + caja + ", ";
                    caja++;
    
                    if (caja > cajas) {
                        break;
                    }
                }
    
                resultado += "\n";
                pallet++;
            }
    
            return resultado;
        } catch (Exception e) {
            return "Error: " + e.getMessage();
        }
    }
    

    /* 
    

        4.	En un juego, cada jugador tiene 3 intentos para sacar cartas de una baraja. Las cartas van numeradas entre 1 y 10. 
        Una función Jugar_21, deberá simular el juego para una cantidad de usuarios que enviará el usuario desde el main entre 1 y 6.

        Para cada uno de los jugadores, el programa le calculará 3 cartas al azar y al final imprimirá el juego para cada jugador basado en las siguientes reglas: 
        
        Si saca 21 exactos: juego perfecto
        Si saca más de 21: se pasó
        Si saca menos de 21: faltaron puntos

        La función deberá imprimir los puntos de cada jugador junto con la regla anterior, como muestra el ejemplo:

        Jugador X, puntos 21 -- > juego perfecto
        Jugador Y, puntos 26 -- > se pasó
        .
        .


    */
    public static String Jugar_21(int jugadores) {
        try {
            if (jugadores < 1 || jugadores > 6) {
                throw new Exception("La cantidad de jugadores debe ser entre 1 y 6.");
            }
    
            final int MIN_CARTAS = 3; // Constant for minimum number of cards
            final int MAX_CARTAS = 10; // Constant for maximum number of cards
    
            Random random = new Random();
            String resultadoFinal = "";
    
            for (int jugador = 1; jugador <= jugadores; jugador++) {
                int puntos = 0;
    
                for (int i = 0; i < MIN_CARTAS; i++) {
                    int carta = random.nextInt(MAX_CARTAS) + 1; // Generate a random number between 1 and 10
                    puntos += carta;
                }
    
                String resultado = "";
    
                if (puntos == 21) {
                    resultado = "juego perfecto";
                } else if (puntos > 21) {
                    resultado = "se pasó";
                } else {
                    resultado = "faltaron puntos";
                }
    
                resultadoFinal += "Jugador " + jugador + ", puntos " + puntos + " --> " + resultado + "\n";
            }
    
            return resultadoFinal;
        } catch (Exception e) {
            return "Error: " + e.getMessage();
        }
    }



}
